### ISSUE TITLE
Does not work with Universal Windows App

### ISSUE THREAD

**Issue by fatichar** [castleproject/castlezmq#9]
Can this be made compatible with Universal Windows Apps? I get following error when trying to install the package:
Castle.Zmq 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).

All other Zeromq bindings for C# also have the same problem. Is there a technical reason for this?

**Comment by jonorossi** [comment]
As you already know Castle.Zmq and clrzmq4 are just bindings, they wrap the native libzmq library which doesn't look like it is supported on the Universal Windows Platform. NetMQ (the all managed C# implementation) is also not supported on the UWP because it looks like there are [missing socket APIs](https://github.com/zeromq/netmq/issues/105) but there are likely other problems with it using Win32 calls for IO completion ports.

You could look into compiling libzmq.dll with `/ZW` to find out what APIs aren't available ([MSDN has a guide](https://msdn.microsoft.com/en-us/library/mt186162.aspx?f=255&MSPPError=-2147217396)) and work with the authors before the bindings can be updated, or work with the NetMQ authors to finish the UWP port.

**Comment by hammett** [comment]
Thanks Jono!
